[build]
  # Set a simple build command that does nothing for the frontend.
  # This prevents Netlify from trying to infer and run Node.js-based builds (like node-sass).
  command = ""
  publish = "templates"  # Directory containing your index.html
  functions = "./netlify/functions" # Directory for your Netlify Functions

[functions]
  # The 'python_version' property has been removed.
  # Netlify will now use its default Python version for functions.
  # This resolves the 'Configuration property functions.python_version must be an object' error.

  # Required to include your model directories in the function's deployment package
  # These paths are relative to the project root.
  included_files = [
    "saved_models_usage/**",  # Include all files in this directory and its subdirectories
    "trained_models/**",      # Include all files in this directory and its subdirectories
    "ml_logic.py"             # Include your ML logic file
  ]
